# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0003_auto_20161202_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vassal', to='Sengokuapp.Family'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='gender',
            field=models.CharField(blank=True, choices=[('jj', 'jj'), ('dhd', 'dhd'), ('dsd', 'dsd'), ('bld', 'bld'), ('syd', 'syd'), ('syad', 'syad'), ('nhd', 'nhd'), ('xhd', 'xhd')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='gender',
            field=models.CharField(blank=True, choices=[('jj', 'jj'), ('dhd', 'dhd'), ('dsd', 'dsd'), ('bld', 'bld'), ('syd', 'syd'), ('syad', 'syad'), ('nhd', 'nhd'), ('xhd', 'xhd')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='roads',
            field=models.ManyToManyField(to='Sengokuapp.Road'),
        ),
    ]
