# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0004_auto_20161202_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='photo_add',
            field=models.ImageField(blank=True, null=True, upload_to='domain', verbose_name='upload'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='domain', verbose_name='upload'),
        ),
        migrations.AlterField(
            model_name='family',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Family', verbose_name='upload'),
        ),
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='People', verbose_name='upload'),
        ),
    ]
