# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0005_auto_20161203_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='photo_add_b',
            field=models.ImageField(blank=True, null=True, upload_to='domain_add', verbose_name='upload_add_b'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='photo_add',
            field=models.ImageField(blank=True, null=True, upload_to='domain_add', verbose_name='upload_add'),
        ),
    ]
