# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0006_auto_20161203_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='gender',
            field=models.CharField(blank=True, choices=[('jj', 'jj'), ('dhd', 'dhd'), ('dsd', 'dsd'), ('bld', 'bld'), ('syd', 'syd'), ('syad', 'syad'), ('nhd', 'nhd'), ('xhd', 'xhd')], max_length=200, null=True),
        ),
    ]
