# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0008_auto_20161203_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vassal', to='Sengokuapp.Road'),
        ),
    ]
