# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/uploads/User/幸村.png', null=True, upload_to='User'),
        ),
    ]
