# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0014_auto_20161205_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='User'),
        ),
    ]
