# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sengokuapp', '0017_auto_20161207_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='photo_add',
            field=models.ImageField(blank=True, null=True, upload_to='Family_add', verbose_name='upload_add'),
        ),
    ]
